# Setup
name:         Hi, I'm Travis. A Full Stack Web Developer!
tagline:      I like to make things that look good, and work even better!
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-architect
