# Setup
name:         Hi, I'm Travis!
tagline:      A Web Developer gifted with Illustrative, & UI skills based in Cockeysville, MD.
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-architect
